spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quest-app
    username: postgres
    password: As12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


questapp:
  app:
    secret: questApp
  expires:
    in: 3600000
  refresh:
    token:
      expires:
        in: 604800